In [71]:
import pandas as pd

df = pd.read_csv("pivoted_vltsdb_kwversion_hourly_resampled.csv")
df

,interval_end,00374f87-909c-6ef8-847f-a7b4694ad804,0101ee7c-a0ef-7b94-f62b-594142c8b0e6,012091d7-8dfd-1322-28e4-4a3c57b067c7,02f4e241-53ef-7fb8-ff1d-ba17643d7645,02fb6917-572b-6e82-8f53-2dd1fb188a3c,0359f57d-5a06-40c6-3d83-4a0a7720eba1,03dde450-8366-1cb8-1632-f6c8135b8077,0414cdc3-fc98-163e-3e99-6c42cb74181f,0644edc0-0417-d12c-b3cb-505bc2e3e258,...,fa27bfb9-9b3e-ace1-bb88-5b95e56f16ba,fa918bd3-d0f3-0e2d-08c6-875ade30fe3e,fadf733b-570c-0e26-247b-f336f42c09d4,fb203000-0b6e-e587-0168-25b53c60a153,fb4fbc9d-bef2-9755-cf57-e481f4cbc83c,fbba4fe0-ad9b-ec46-575c-c22ff0a20186,fc17f9a3-bbf8-5533-ff3e-d3697d614f92,fe6451c9-63c7-b774-496c-9ce8ba6d01af,feba96eb-7c85-a150-dfa6-ed45a7fda60b,feda0965-ac85-b46a-77fe-dc2ad48772fe
0,2015-01-01 05:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2015-01-01 06:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2015-01-01 07:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2015-01-01 08:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015-01-01 09:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33908,2018-11-14 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33909,2018-11-14 02:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33910,2018-11-14 03:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33911,2018-11-14 04:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33912,2018-11-14 05:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [72]:
df.describe()

,00374f87-909c-6ef8-847f-a7b4694ad804,0101ee7c-a0ef-7b94-f62b-594142c8b0e6,012091d7-8dfd-1322-28e4-4a3c57b067c7,02f4e241-53ef-7fb8-ff1d-ba17643d7645,02fb6917-572b-6e82-8f53-2dd1fb188a3c,0359f57d-5a06-40c6-3d83-4a0a7720eba1,03dde450-8366-1cb8-1632-f6c8135b8077,0414cdc3-fc98-163e-3e99-6c42cb74181f,0644edc0-0417-d12c-b3cb-505bc2e3e258,07ae0994-02e6-2b53-051f-609e8d9efa1e,...,fa27bfb9-9b3e-ace1-bb88-5b95e56f16ba,fa918bd3-d0f3-0e2d-08c6-875ade30fe3e,fadf733b-570c-0e26-247b-f336f42c09d4,fb203000-0b6e-e587-0168-25b53c60a153,fb4fbc9d-bef2-9755-cf57-e481f4cbc83c,fbba4fe0-ad9b-ec46-575c-c22ff0a20186,fc17f9a3-bbf8-5533-ff3e-d3697d614f92,fe6451c9-63c7-b774-496c-9ce8ba6d01af,feba96eb-7c85-a150-dfa6-ed45a7fda60b,feda0965-ac85-b46a-77fe-dc2ad48772fe
count,33913.000000,33913.0,33913.000000,33913.000000,33913.000000,33913.000000,33913.000000,33913.000000,33913.000000,33913.0,...,33913.000000,33913.000000,33913.000000,33913.000000,33913.000000,33913.000000,33913.000000,33913.000000,33913.000000,33913.000000
mean,4712.293368,0.0,5608.383107,1649.585382,117.656763,1.323641,151.675465,181.587646,905.954280,0.0,...,0.955131,134.099947,1.303288,7517.342288,1.270602,813.000413,1567.344723,1.545423,465.529424,1.506018
std,2773.546225,0.0,3997.020676,983.221794,132.641854,15.457092,150.259951,322.649203,449.459447,0.0,...,10.990504,147.979893,17.366707,4895.523603,14.617356,946.250916,628.961097,18.115364,374.087318,17.022721
min,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2735.100000,0.0,2764.800000,923.400000,0.000000,0.000000,0.000000,0.000000,720.000000,0.0,...,0.000000,0.000000,0.000000,3267.000000,0.000000,0.000000,1580.800000,0.000000,0.000000,0.000000
50%,4195.800000,0.0,3866.400000,1639.800000,73.500000,0.000000,159.780000,0.000000,898.200000,0.0,...,0.000000,63.075000,0.000000,7074.000000,0.000000,95.040000,1689.600000,0.000000,468.720000,0.000000
75%,7335.900000,0.0,9455.400000,2442.600000,241.500000,0.000000,294.405000,295.744000,1188.000000,0.0,...,0.000000,290.550000,0.000000,11574.000000,0.000000,1661.760000,1854.720000,0.000000,717.120000,0.000000
max,10076.400000,0.0,16507.800000,4456.800000,507.500000,243.840000,482.490000,1418.688000,2462.400000,0.0,...,158.400000,480.525000,288.000000,20079.000000,228.800000,3637.440000,2649.600000,295.040000,1722.960000,218.240000

In [73]:
from adtk.data import validate_series
from adtk.detector import SeasonalAD

df.index = df.interval_end
df.idex = pd.to_datetime(df.index)


seasonal_ids = ['00374f87-909c-6ef8-847f-a7b4694ad804',
 '00374f87-909c-6ef8-847f-a7b4694ad804',
 '012091d7-8dfd-1322-28e4-4a3c57b067c7',
 '012091d7-8dfd-1322-28e4-4a3c57b067c7',
 '02f4e241-53ef-7fb8-ff1d-ba17643d7645',
 '02f4e241-53ef-7fb8-ff1d-ba17643d7645',
 '02fb6917-572b-6e82-8f53-2dd1fb188a3c',
 '03dde450-8366-1cb8-1632-f6c8135b8077',
 '0644edc0-0417-d12c-b3cb-505bc2e3e258',
 '08737ad9-2384-03d2-6557-83958fc5d881',
 '08737ad9-2384-03d2-6557-83958fc5d881',
 '08ff275a-aaf6-bda6-7df1-2730c9ab29b7',
 '08ff275a-aaf6-bda6-7df1-2730c9ab29b7',
 '09473fb0-9258-71fa-827b-fabb32404ca6',
 '11a7bb84-7601-0161-9588-b9b5020518e5',
 '11ba23cb-dfd8-bf06-3ab1-7ac4ad6f1d5c',
 '1374c5d3-9816-3f20-2d93-73e81fe6892f',
 '168c044a-2cc8-92b6-fe42-806449544be4',
 '1c82b217-174d-63af-01b2-2e0d35c85cd2',
 '1d07f991-8621-bbc8-d597-39c6b125f662',
 '1d07f991-8621-bbc8-d597-39c6b125f662',
 '20091471-e961-3d8d-0cf7-b686dff662d4',
 '22f70f53-453d-9f22-24ca-b62a313ca6aa',
 '269d0b8a-8350-36b4-67c3-3e29d6041b5c',
 '275e824c-e88d-8389-18a9-21e2d0e0d0f6',
 '275e824c-e88d-8389-18a9-21e2d0e0d0f6',
 '27834896-8120-34d1-ffea-2b9006ef3ab2',
 '281e2b26-89bc-2a2c-f5b7-322f942d139d',
 '28c08889-a891-54e1-6b6c-bf685b9ee343',
 '291a7e63-beb1-09b7-601c-93c326be0607',
 '318467ad-e593-a20a-fe23-daf9998cc991',
 '33450d85-96f7-df00-50f6-0afe4b72ab2f',
 '3397f38f-2dfc-97a0-eba9-770dd94c89b2',
 '3397f38f-2dfc-97a0-eba9-770dd94c89b2',
 '35834753-fd0f-ebc7-ba6d-27c9c8de1656',
 '35d54699-97cc-50f2-6d5c-5d50607e9631',
 '35d54699-97cc-50f2-6d5c-5d50607e9631',
 '3c1338ac-67bd-38a2-f3c2-2c362ce6b5c0',
 '3f461171-89c5-fd7f-8e4a-1483094e74c2',
 '3feaeec7-c201-c614-d067-1c6db38f2255',
 '42c0a431-7e11-212b-ce75-b13e7ea4338c',
 '42c0c45f-f378-fb9d-6efe-175c1b784a3a',
 '4721a1d8-197d-36f8-0a79-a2f3819ead5d',
 '4721a1d8-197d-36f8-0a79-a2f3819ead5d',
 '5262ce23-8185-85d4-08d2-0a7fe031f563',
 '542f6bfc-a1d2-620f-a1f1-464a7c274a69',
 '549c315b-6263-d161-8762-d46d1ed5ca34',
 '549eebeb-2468-755b-3110-c3080e17eabd',
 '549eebeb-2468-755b-3110-c3080e17eabd',
 '5961e490-81ba-c338-86cd-ad5c7919ee60',
 '5a717cb9-181c-1d40-e12f-a2777bc78952',
 '5af67d8c-1379-a6e1-6014-5507848a20f7',
 '5f10fb10-ef38-c5a1-10c4-7ae824cf2932',
 '61ff3699-aad4-35d3-4ecb-b8195e8b08cd',
 '62956e4f-600f-ebbe-c147-be502c139aea',
 '62956e4f-600f-ebbe-c147-be502c139aea',
 '62bca157-801c-d9df-de16-8d9b286db265',
 '66e9c85d-6b5f-d012-4b56-f69218073f86',
 '67558069-06d2-2b8a-e0a8-18cc5444c287',
 '6f375f3e-7bc8-3b7f-e3bd-77378d0c22c7',
 '71cd23cb-cf0c-1c17-8bee-3d5e0eaf60f2',
 '72429eca-0240-b236-1d1a-7f629bc2a9d9',
 '79ae3c7c-f1a1-90e7-c526-057e26a34eca',
 '7bbf216b-e46a-70c5-2359-87e5fdc86737',
 '7bbf216b-e46a-70c5-2359-87e5fdc86737',
 '7d167b7b-2871-1c6d-a474-8accad23bb94',
 '7d167b7b-2871-1c6d-a474-8accad23bb94',
 '7e1cc7bc-6e8b-6546-2cf1-f8027dc18fe5',
 '80003fc3-a5cc-a190-a51e-1861cc7ffe03',
 '871fe49b-fe9e-b4f9-dbef-5054703fcd68',
 '8cc22eef-f6b8-8bb8-7a7d-e535f80d9a9f',
 '8d7108e3-ac36-ba4a-ad12-34b6ebe6664c',
 '9aa3b5ad-0981-1a44-d58d-e3f2d1f2d550',
 '9e5958d7-e707-bb5f-826a-2ee8c17bf297',
 'a03f0e3d-e65c-be54-d81f-8d29058cada5',
 'a075bba6-b74c-d462-7462-0020ac636a3f',
 'a2bace58-b2d3-7df7-b5d0-f471508a6819',
 'a3af4ff8-d1aa-331b-d3fd-814b84257c56',
 'a4025fa5-e903-6079-7f04-38357974d0e0',
 'a8a44573-c3c1-c4d4-c0bb-03bb7ecddace',
 'ab2b089d-89fb-c0dc-85db-a37aea780a0e',
 'ab2b089d-89fb-c0dc-85db-a37aea780a0e',
 'b3419bd8-785d-6ca5-3326-7219ad96c641',
 'b6fd0560-0ae2-f650-2d0c-0d92e988af6e',
 'b6fd0560-0ae2-f650-2d0c-0d92e988af6e',
 'b7386659-1010-f92c-4f4f-31b5b1f907c5',
 'b8ec0850-c5ce-1579-5438-8d1247f0ff16',
 'bb6d4ebb-6353-7fca-87f2-d4edbf573fcc',
 'bb6d4ebb-6353-7fca-87f2-d4edbf573fcc',
 'c388dd30-eaeb-dcfe-f76e-e2e6ebf83ce1',
 'c478ba56-575c-c594-b016-7d3061bd9b3b',
 'c8457bd6-c454-d94d-393e-4561f0599a06',
 'c966b497-d639-dadc-60b5-248687103a2d',
 'cb8d68c3-d6e6-215a-eca2-b969bed491af',
 'cc7bb9d3-3ef7-979e-1603-70fa8dbcb70e',
 'cd72b978-a4fa-c81e-6e90-14892bde8473',
 'cd72b978-a4fa-c81e-6e90-14892bde8473',
 'ce975f7d-c364-6d48-0a2c-ba17b480fe8c',
 'ceecdd19-18fd-a6ed-ddd0-30f2a6af6b5b',
 'd4657704-6015-5cc2-1293-c4f85d4ef86e',
 'd5e319d6-b7e6-f902-8aa7-a740ffdf3ef6',
 'd66979ba-4d38-6ebc-865b-e9e28936f289',
 'd787f244-dfa2-59b2-d1e2-c5156e632285',
 'd8db3e51-15b2-6789-eccc-0d0573239b2f',
 'dbea811b-92f8-4e35-432c-9a7d19680a6d',
 'dc59faa0-5478-3c1a-9d24-e0c6eb7a6c4e',
 'dcfda865-19c7-db9d-79f7-62975d5e11d5',
 'de6f7118-06d2-45e8-1a7a-b30e07e233f7',
 'debc4593-d7e7-c1ae-f268-f6944c531e3f',
 'e4bf9a40-a95c-6488-cc12-9dfdeb781be6',
 'e5d06e7f-d057-24d9-b417-118c206cbd7e',
 'e7d819a2-4382-e7d1-a267-069c96a54333',
 'e9386ab1-439f-2878-6c65-fa440370f73b',
 'ea0bee90-5500-25e3-1483-5ca53f8b0d82',
 'ea0bee90-5500-25e3-1483-5ca53f8b0d82',
 'eba417ce-b125-8595-6b56-11f89c2f09b8',
 'eccea137-1478-4434-9694-6456ee9d4674',
 'ee9e572d-9840-3093-811f-941b7f48e73f',
 'f2f57d71-344e-adda-6441-3b7d6620dd40',
 'f58c29d4-da39-b21a-6280-579f4b04af08',
 'f642e2d0-64fb-a3a4-82a3-1e6c9374f0ae',
 'f7cb6999-e8e4-8dc2-a609-4b1b5c0ca9c9',
 'f7cb6999-e8e4-8dc2-a609-4b1b5c0ca9c9',
 'f81d7812-364c-67ba-2379-bd4b8a6a87ba',
 'fa1e6d9b-9562-02aa-0a4a-3f08fdf1c960',
 'fa918bd3-d0f3-0e2d-08c6-875ade30fe3e',
 'fb203000-0b6e-e587-0168-25b53c60a153']


all_event = pd.DataFrame()
for ids in seasonal_ids:
    df_test = df[[ids]]
    df_test.index = pd.to_datetime(df_test.index)
    s_train = validate_series(df_test)
    seasonal_ad = SeasonalAD()
    anomalies = seasonal_ad.fit_detect(s_train)
    all_event = all_event.append(anomalies.loc[anomalies.iloc[:,0] == True])
    print(anomalies.loc[anomalies.iloc[:,0] == True])

all_event.to_csv('all_dr_event_vlts.csv')

/Users/abulhasanfahad/opt/anaconda3/envs/ml/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """

                     00374f87-909c-6ef8-847f-a7b4694ad804
interval_end
2015-01-01 10:00:00                                  True
2015-01-01 11:00:00                                  True
2015-01-01 12:00:00                                  True
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
...                                                   ...
2018-11-13 19:00:00                                  True
2018-11-13 20:00:00                                  True
2018-11-13 21:00:00                                  True
2018-11-13 22:00:00                                  True
2018-11-13 23:00:00                                  True

[1655 rows x 1 columns]
                     00374f87-909c-6ef8-847f-a7b4694ad804
interval_end
2015-01-01 10:00:00                                  True
2015-01-01 11:00:00                                  True
2015-01-01 12:00:00                                  True
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
...                                                   ...
2018-11-13 19:00:00                                  True
2018-11-13 20:00:00                                  True
2018-11-13 21:00:00                                  True
2018-11-13 22:00:00                                  True
2018-11-13 23:00:00                                  True

[1655 rows x 1 columns]
                     012091d7-8dfd-1322-28e4-4a3c57b067c7
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True

[750 rows x 1 columns]
                     012091d7-8dfd-1322-28e4-4a3c57b067c7
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True

[750 rows x 1 columns]
                     02f4e241-53ef-7fb8-ff1d-ba17643d7645
interval_end
2017-07-06 06:00:00                                  True
                     02f4e241-53ef-7fb8-ff1d-ba17643d7645
interval_end
2017-07-06 06:00:00                                  True
Empty DataFrame
Columns: [02fb6917-572b-6e82-8f53-2dd1fb188a3c]
Index: []
Empty DataFrame
Columns: [03dde450-8366-1cb8-1632-f6c8135b8077]
Index: []
                     0644edc0-0417-d12c-b3cb-505bc2e3e258
interval_end
2016-08-09 18:00:00                                  True
2016-08-24 15:00:00                                  True
2016-08-24 16:00:00                                  True
2016-08-24 17:00:00                                  True
2016-08-24 18:00:00                                  True
2016-08-25 15:00:00                                  True
2016-08-25 17:00:00                                  True
2016-08-25 18:00:00                                  True
2016-08-25 19:00:00                                  True
2016-09-07 17:00:00                                  True
2016-09-08 14:00:00                                  True
2016-09-08 15:00:00                                  True
2016-09-08 17:00:00                                  True
2018-05-29 15:00:00                                  True
2018-05-29 16:00:00                                  True
2018-05-29 17:00:00                                  True
2018-08-27 14:00:00                                  True
2018-08-27 15:00:00                                  True
2018-08-27 16:00:00                                  True
2018-08-28 15:00:00                                  True
2018-08-28 16:00:00                                  True
2018-08-28 17:00:00                                  True
2018-08-29 16:00:00                                  True
2018-08-29 17:00:00                                  True
2018-08-29 18:00:00                                  True
2018-09-05 14:00:00                                  True
2018-09-05 16:00:00                                  True
2018-09-05 17:00:00                                  True
2018-09-06 12:00:00                                  True
2018-09-07 17:00:00                                  True
2018-09-14 14:00:00                                  True
                     08737ad9-2384-03d2-6557-83958fc5d881
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 22:00:00                                  True
2018-11-13 23:00:00                                  True
2018-11-14 00:00:00                                  True
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True

[862 rows x 1 columns]
                     08737ad9-2384-03d2-6557-83958fc5d881
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 22:00:00                                  True
2018-11-13 23:00:00                                  True
2018-11-14 00:00:00                                  True
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True

[862 rows x 1 columns]
                     08ff275a-aaf6-bda6-7df1-2730c9ab29b7
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True
2018-11-13 20:00:00                                  True

[1115 rows x 1 columns]
                     08ff275a-aaf6-bda6-7df1-2730c9ab29b7
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True
2018-11-13 20:00:00                                  True

[1115 rows x 1 columns]
                     09473fb0-9258-71fa-827b-fabb32404ca6
interval_end
2017-08-01 11:00:00                                  True
2017-08-01 12:00:00                                  True
2017-08-01 13:00:00                                  True
2017-08-01 14:00:00                                  True
2017-08-01 15:00:00                                  True
...                                                   ...
2018-07-31 21:00:00                                  True
2018-07-31 22:00:00                                  True
2018-07-31 23:00:00                                  True
2018-08-01 00:00:00                                  True
2018-08-01 01:00:00                                  True

[2599 rows x 1 columns]

                     11a7bb84-7601-0161-9588-b9b5020518e5
interval_end
2015-06-21 17:00:00                                  True
2015-07-18 18:00:00                                  True
2015-07-29 18:00:00                                  True
2015-07-29 19:00:00                                  True
2015-07-29 20:00:00                                  True
...                                                   ...
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True
2018-11-14 03:00:00                                  True
2018-11-14 04:00:00                                  True
2018-11-14 05:00:00                                  True

[670 rows x 1 columns]
Empty DataFrame
Columns: [11ba23cb-dfd8-bf06-3ab1-7ac4ad6f1d5c]
Index: []
Empty DataFrame
Columns: [1374c5d3-9816-3f20-2d93-73e81fe6892f]
Index: []
                     168c044a-2cc8-92b6-fe42-806449544be4
interval_end
2018-06-01 17:00:00                                  True
2018-06-18 12:00:00                                  True
2018-06-18 13:00:00                                  True
2018-06-18 14:00:00                                  True
2018-06-18 15:00:00                                  True
...                                                   ...
2018-09-06 16:00:00                                  True
2018-09-06 17:00:00                                  True
2018-09-06 18:00:00                                  True
2018-09-07 16:00:00                                  True
2018-09-07 17:00:00                                  True

[69 rows x 1 columns]
Empty DataFrame
Columns: [1c82b217-174d-63af-01b2-2e0d35c85cd2]
Index: []
                     1d07f991-8621-bbc8-d597-39c6b125f662
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 14:00:00                                  True
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True

[1151 rows x 1 columns]
                     1d07f991-8621-bbc8-d597-39c6b125f662
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 14:00:00                                  True
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True

[1151 rows x 1 columns]
Empty DataFrame
Columns: [20091471-e961-3d8d-0cf7-b686dff662d4]
Index: []
                     22f70f53-453d-9f22-24ca-b62a313ca6aa
interval_end
2015-02-15 03:00:00                                  True
2015-02-16 03:00:00                                  True
2015-02-17 03:00:00                                  True
2015-02-24 03:00:00                                  True
2015-12-22 05:00:00                                  True
...                                                   ...
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True
2018-11-14 03:00:00                                  True
2018-11-14 04:00:00                                  True
2018-11-14 05:00:00                                  True

[598 rows x 1 columns]
                     269d0b8a-8350-36b4-67c3-3e29d6041b5c
interval_end
2017-09-06 15:00:00                                  True
2017-09-06 16:00:00                                  True
2017-09-06 17:00:00                                  True
2017-09-06 18:00:00                                  True
2017-09-06 19:00:00                                  True
...                                                   ...
2018-10-01 13:00:00                                  True
2018-10-02 01:00:00                                  True
2018-10-02 02:00:00                                  True
2018-10-02 03:00:00                                  True
2018-10-02 04:00:00                                  True

[3216 rows x 1 columns]
                     275e824c-e88d-8389-18a9-21e2d0e0d0f6
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True

[1078 rows x 1 columns]
                     275e824c-e88d-8389-18a9-21e2d0e0d0f6
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True

[1078 rows x 1 columns]
                     27834896-8120-34d1-ffea-2b9006ef3ab2
interval_end
2017-08-01 14:00:00                                  True
2017-08-01 15:00:00                                  True
2017-08-01 16:00:00                                  True
2017-08-01 17:00:00                                  True
2017-08-01 18:00:00                                  True
...                                                   ...
2018-08-28 17:00:00                                  True
2018-08-28 18:00:00                                  True
2018-08-28 23:00:00                                  True
2018-08-29 00:00:00                                  True
2018-08-29 01:00:00                                  True

[1880 rows x 1 columns]
Empty DataFrame
Columns: [281e2b26-89bc-2a2c-f5b7-322f942d139d]
Index: []
Empty DataFrame
Columns: [28c08889-a891-54e1-6b6c-bf685b9ee343]
Index: []
                     291a7e63-beb1-09b7-601c-93c326be0607
interval_end
2017-08-20 19:00:00                                  True
2017-09-26 17:00:00                                  True
2017-09-26 19:00:00                                  True
2018-05-16 22:00:00                                  True
2018-05-16 23:00:00                                  True
2018-05-29 15:00:00                                  True
2018-05-29 16:00:00                                  True
2018-05-29 17:00:00                                  True
2018-05-29 18:00:00                                  True
2018-05-29 19:00:00                                  True
2018-05-30 17:00:00                                  True
2018-05-30 18:00:00                                  True
2018-06-18 12:00:00                                  True
2018-06-18 13:00:00                                  True
2018-06-18 14:00:00                                  True
2018-06-18 15:00:00                                  True
2018-06-18 16:00:00                                  True
2018-06-18 18:00:00                                  True
2018-06-18 19:00:00                                  True
2018-08-07 10:00:00                                  True
2018-08-27 13:00:00                                  True
2018-08-27 14:00:00                                  True
2018-08-27 15:00:00                                  True
2018-08-27 16:00:00                                  True
2018-08-27 19:00:00                                  True
2018-08-28 15:00:00                                  True
2018-08-28 18:00:00                                  True
2018-08-28 19:00:00                                  True
2018-08-29 15:00:00                                  True
2018-08-29 16:00:00                                  True
2018-08-29 17:00:00                                  True
2018-08-29 18:00:00                                  True
2018-08-29 19:00:00                                  True
2018-09-04 07:00:00                                  True
2018-09-04 13:00:00                                  True
2018-09-04 14:00:00                                  True
2018-09-04 15:00:00                                  True
2018-09-04 16:00:00                                  True
2018-09-04 17:00:00                                  True
2018-09-04 18:00:00                                  True
2018-09-04 19:00:00                                  True
2018-09-04 20:00:00                                  True
2018-09-04 21:00:00                                  True
2018-09-05 15:00:00                                  True
2018-09-05 16:00:00                                  True
2018-09-05 17:00:00                                  True
2018-09-05 19:00:00                                  True
2018-09-05 20:00:00                                  True
2018-09-05 21:00:00                                  True
2018-09-21 17:00:00                                  True
2018-09-21 18:00:00                                  True
2018-09-21 19:00:00                                  True
                     318467ad-e593-a20a-fe23-daf9998cc991
interval_end
2017-08-01 16:00:00                                  True
2017-08-01 17:00:00                                  True
2017-08-01 18:00:00                                  True
2017-08-01 19:00:00                                  True
2017-08-01 20:00:00                                  True
...                                                   ...
2018-09-21 19:00:00                                  True
2018-09-21 20:00:00                                  True
2018-09-22 00:00:00                                  True
2018-09-22 01:00:00                                  True
2018-10-11 11:00:00                                  True

[439 rows x 1 columns]

Empty DataFrame
Columns: [33450d85-96f7-df00-50f6-0afe4b72ab2f]
Index: []
Empty DataFrame
Columns: [3397f38f-2dfc-97a0-eba9-770dd94c89b2]
Index: []
Empty DataFrame
Columns: [3397f38f-2dfc-97a0-eba9-770dd94c89b2]
Index: []
Empty DataFrame
Columns: [35834753-fd0f-ebc7-ba6d-27c9c8de1656]
Index: []
                     35d54699-97cc-50f2-6d5c-5d50607e9631
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 13:00:00                                  True
2018-11-13 14:00:00                                  True
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True

[435 rows x 1 columns]
                     35d54699-97cc-50f2-6d5c-5d50607e9631
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 13:00:00                                  True
2018-11-13 14:00:00                                  True
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True

[435 rows x 1 columns]
                     3c1338ac-67bd-38a2-f3c2-2c362ce6b5c0
interval_end
2015-07-19 14:00:00                                  True
2015-07-19 16:00:00                                  True
2015-07-19 17:00:00                                  True
2015-07-19 18:00:00                                  True
2015-07-21 11:00:00                                  True
2015-07-21 14:00:00                                  True
2015-07-21 15:00:00                                  True
2015-07-21 16:00:00                                  True
2015-07-21 17:00:00                                  True
2015-07-21 18:00:00                                  True
2015-08-10 13:00:00                                  True
2015-08-10 15:00:00                                  True
2015-08-10 16:00:00                                  True
2015-08-10 17:00:00                                  True
2016-08-06 11:00:00                                  True
2016-08-06 12:00:00                                  True
2017-07-21 12:00:00                                  True
2017-07-21 13:00:00                                  True
2018-05-15 18:00:00                                  True
2018-07-26 12:00:00                                  True
                     3f461171-89c5-fd7f-8e4a-1483094e74c2
interval_end
2018-08-07 17:00:00                                  True
2018-08-28 14:00:00                                  True
2018-08-28 15:00:00                                  True
2018-08-29 11:00:00                                  True
2018-08-29 14:00:00                                  True
2018-08-29 15:00:00                                  True
2018-09-06 12:00:00                                  True
2018-09-06 13:00:00                                  True
2018-09-06 14:00:00                                  True
2018-09-06 15:00:00                                  True
2018-09-06 16:00:00                                  True
Empty DataFrame
Columns: [3feaeec7-c201-c614-d067-1c6db38f2255]
Index: []
                     42c0a431-7e11-212b-ce75-b13e7ea4338c
interval_end
2015-01-07 18:00:00                                  True
2015-01-07 19:00:00                                  True
2015-01-14 18:00:00                                  True
2015-01-14 19:00:00                                  True
2015-01-21 18:00:00                                  True
2015-01-21 19:00:00                                  True
2015-01-28 18:00:00                                  True
2015-01-28 19:00:00                                  True
2015-02-04 18:00:00                                  True
2015-02-04 19:00:00                                  True
2015-02-11 18:00:00                                  True
2015-02-11 19:00:00                                  True
2015-02-18 18:00:00                                  True
2015-02-18 19:00:00                                  True
2015-02-25 18:00:00                                  True
2015-02-25 19:00:00                                  True
2015-03-04 18:00:00                                  True
2015-03-04 19:00:00                                  True
2015-03-11 18:00:00                                  True
2015-03-11 19:00:00                                  True
2015-03-18 18:00:00                                  True
2015-03-18 19:00:00                                  True
2015-03-25 18:00:00                                  True
2015-03-25 19:00:00                                  True
2015-04-01 18:00:00                                  True
2015-04-01 19:00:00                                  True
2015-04-08 18:00:00                                  True
2015-04-08 19:00:00                                  True
2015-04-15 18:00:00                                  True
2015-04-15 19:00:00                                  True
2015-04-22 18:00:00                                  True
2015-04-22 19:00:00                                  True
2015-04-29 18:00:00                                  True
2015-04-29 19:00:00                                  True
2015-05-06 18:00:00                                  True
2015-05-06 19:00:00                                  True
2015-05-13 18:00:00                                  True
2015-05-13 19:00:00                                  True
2016-01-23 15:00:00                                  True
2018-10-17 18:00:00                                  True
2018-10-17 19:00:00                                  True
2018-10-24 18:00:00                                  True
2018-10-24 19:00:00                                  True
2018-10-31 18:00:00                                  True
2018-10-31 19:00:00                                  True
2018-11-07 18:00:00                                  True
2018-11-07 19:00:00                                  True
                     42c0c45f-f378-fb9d-6efe-175c1b784a3a
interval_end
2016-08-30 23:00:00                                  True
2016-08-31 05:00:00                                  True
2016-09-08 18:00:00                                  True
2017-06-12 17:00:00                                  True
2017-06-12 18:00:00                                  True
2017-06-20 20:00:00                                  True
2017-08-03 19:00:00                                  True
2017-08-04 16:00:00                                  True
2018-07-10 18:00:00                                  True
2018-08-06 18:00:00                                  True
                     4721a1d8-197d-36f8-0a79-a2f3819ead5d
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 22:00:00                                  True
2018-11-13 23:00:00                                  True
2018-11-14 00:00:00                                  True
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True

[861 rows x 1 columns]

                     4721a1d8-197d-36f8-0a79-a2f3819ead5d
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 22:00:00                                  True
2018-11-13 23:00:00                                  True
2018-11-14 00:00:00                                  True
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True

[861 rows x 1 columns]
                     5262ce23-8185-85d4-08d2-0a7fe031f563
interval_end
2015-01-01 22:00:00                                  True
2015-01-01 23:00:00                                  True
2015-01-02 00:00:00                                  True
2015-01-02 01:00:00                                  True
2015-01-02 22:00:00                                  True
...                                                   ...
2018-11-13 01:00:00                                  True
2018-11-13 22:00:00                                  True
2018-11-13 23:00:00                                  True
2018-11-14 00:00:00                                  True
2018-11-14 01:00:00                                  True

[654 rows x 1 columns]
                     542f6bfc-a1d2-620f-a1f1-464a7c274a69
interval_end
2015-05-15 07:00:00                                  True
2015-05-18 22:00:00                                  True
2015-05-29 03:00:00                                  True
2015-05-31 04:00:00                                  True
2015-05-31 05:00:00                                  True
...                                                   ...
2015-12-06 21:00:00                                  True
2015-12-06 22:00:00                                  True
2015-12-14 14:00:00                                  True
2015-12-16 13:00:00                                  True
2015-12-20 15:00:00                                  True

[696 rows x 1 columns]
Empty DataFrame
Columns: [549c315b-6263-d161-8762-d46d1ed5ca34]
Index: []
                     549eebeb-2468-755b-3110-c3080e17eabd
interval_end
2015-05-18 14:00:00                                  True
2015-05-18 15:00:00                                  True
2015-05-29 13:00:00                                  True
2015-05-29 17:00:00                                  True
2015-05-29 18:00:00                                  True
...                                                   ...
2018-10-10 15:00:00                                  True
2018-10-10 16:00:00                                  True
2018-10-10 17:00:00                                  True
2018-10-10 18:00:00                                  True
2018-10-10 19:00:00                                  True

[257 rows x 1 columns]
                     549eebeb-2468-755b-3110-c3080e17eabd
interval_end
2015-05-18 14:00:00                                  True
2015-05-18 15:00:00                                  True
2015-05-29 13:00:00                                  True
2015-05-29 17:00:00                                  True
2015-05-29 18:00:00                                  True
...                                                   ...
2018-10-10 15:00:00                                  True
2018-10-10 16:00:00                                  True
2018-10-10 17:00:00                                  True
2018-10-10 18:00:00                                  True
2018-10-10 19:00:00                                  True

[257 rows x 1 columns]
                     5961e490-81ba-c338-86cd-ad5c7919ee60
interval_end
2015-01-02 00:00:00                                  True
2015-01-03 00:00:00                                  True
2015-01-03 01:00:00                                  True
2015-01-04 00:00:00                                  True
2015-01-04 01:00:00                                  True
...                                                   ...
2018-11-13 00:00:00                                  True
2018-11-13 01:00:00                                  True
2018-11-13 23:00:00                                  True
2018-11-14 00:00:00                                  True
2018-11-14 01:00:00                                  True

[315 rows x 1 columns]
                     5a717cb9-181c-1d40-e12f-a2777bc78952
interval_end
2015-12-16 04:00:00                                  True
2016-03-09 06:00:00                                  True
2016-09-21 04:00:00                                  True
2016-09-21 05:00:00                                  True
2016-09-22 06:00:00                                  True
2016-09-22 07:00:00                                  True
2016-09-29 06:00:00                                  True
2016-09-29 07:00:00                                  True
2016-09-30 04:00:00                                  True
2016-11-01 07:00:00                                  True
2016-11-02 04:00:00                                  True
2016-12-09 05:00:00                                  True
2017-04-24 04:00:00                                  True
2017-09-25 04:00:00                                  True
2018-10-11 04:00:00                                  True
2018-10-11 06:00:00                                  True
2018-10-11 07:00:00                                  True
2018-10-11 08:00:00                                  True
Empty DataFrame
Columns: [5af67d8c-1379-a6e1-6014-5507848a20f7]
Index: []
Empty DataFrame
Columns: [5f10fb10-ef38-c5a1-10c4-7ae824cf2932]
Index: []
                     61ff3699-aad4-35d3-4ecb-b8195e8b08cd
interval_end
2016-02-29 09:00:00                                  True
2017-06-19 19:00:00                                  True
2018-06-08 04:00:00                                  True
2018-06-08 06:00:00                                  True
2018-06-08 07:00:00                                  True
...                                                   ...
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True
2018-11-14 03:00:00                                  True
2018-11-14 04:00:00                                  True
2018-11-14 05:00:00                                  True

[568 rows x 1 columns]
                     62956e4f-600f-ebbe-c147-be502c139aea
interval_end
2015-01-01 12:00:00                                  True
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
...                                                   ...
2018-11-13 14:00:00                                  True
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True

[1328 rows x 1 columns]
                     62956e4f-600f-ebbe-c147-be502c139aea
interval_end
2015-01-01 12:00:00                                  True
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
...                                                   ...
2018-11-13 14:00:00                                  True
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True

[1328 rows x 1 columns]

                     62bca157-801c-d9df-de16-8d9b286db265
interval_end
2016-06-01 15:00:00                                  True
2016-06-01 16:00:00                                  True
2016-06-01 18:00:00                                  True
2016-06-01 19:00:00                                  True
2016-06-01 20:00:00                                  True
...                                                   ...
2016-09-23 19:00:00                                  True
2016-09-23 20:00:00                                  True
2016-11-02 15:00:00                                  True
2018-08-27 16:00:00                                  True
2018-08-27 17:00:00                                  True

[100 rows x 1 columns]
                     66e9c85d-6b5f-d012-4b56-f69218073f86
interval_end
2018-07-11 01:00:00                                  True
2018-07-11 02:00:00                                  True
2018-07-11 03:00:00                                  True
Empty DataFrame
Columns: [67558069-06d2-2b8a-e0a8-18cc5444c287]
Index: []
Empty DataFrame
Columns: [6f375f3e-7bc8-3b7f-e3bd-77378d0c22c7]
Index: []
Empty DataFrame
Columns: [71cd23cb-cf0c-1c17-8bee-3d5e0eaf60f2]
Index: []
                     72429eca-0240-b236-1d1a-7f629bc2a9d9
interval_end
2017-08-01 17:00:00                                  True
2017-08-01 18:00:00                                  True
2017-08-01 19:00:00                                  True
2017-08-01 20:00:00                                  True
2017-08-01 21:00:00                                  True
...                                                   ...
2018-09-05 23:00:00                                  True
2018-09-06 00:00:00                                  True
2018-09-06 01:00:00                                  True
2018-09-07 00:00:00                                  True
2018-09-07 01:00:00                                  True

[1352 rows x 1 columns]
Empty DataFrame
Columns: [79ae3c7c-f1a1-90e7-c526-057e26a34eca]
Index: []
                     7bbf216b-e46a-70c5-2359-87e5fdc86737
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True

[773 rows x 1 columns]
                     7bbf216b-e46a-70c5-2359-87e5fdc86737
interval_end
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
...                                                   ...
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True

[773 rows x 1 columns]
Empty DataFrame
Columns: [7d167b7b-2871-1c6d-a474-8accad23bb94]
Index: []
Empty DataFrame
Columns: [7d167b7b-2871-1c6d-a474-8accad23bb94]
Index: []
                     7e1cc7bc-6e8b-6546-2cf1-f8027dc18fe5
interval_end
2015-07-19 19:00:00                                  True
2017-05-01 19:00:00                                  True
2017-05-01 20:00:00                                  True
2017-08-05 01:00:00                                  True
2017-08-05 02:00:00                                  True
...                                                   ...
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True
2018-11-14 03:00:00                                  True
2018-11-14 04:00:00                                  True
2018-11-14 05:00:00                                  True

[572 rows x 1 columns]
Empty DataFrame
Columns: [80003fc3-a5cc-a190-a51e-1861cc7ffe03]
Index: []
Empty DataFrame
Columns: [871fe49b-fe9e-b4f9-dbef-5054703fcd68]
Index: []
                     8cc22eef-f6b8-8bb8-7a7d-e535f80d9a9f
interval_end
2017-08-02 01:00:00                                  True
2017-08-03 01:00:00                                  True
2017-08-04 01:00:00                                  True
2017-08-05 01:00:00                                  True
2017-08-19 01:00:00                                  True
...                                                   ...
2018-09-05 17:00:00                                  True
2018-09-05 18:00:00                                  True
2018-09-06 00:00:00                                  True
2018-09-06 01:00:00                                  True
2018-09-15 19:00:00                                  True

[111 rows x 1 columns]
                     8d7108e3-ac36-ba4a-ad12-34b6ebe6664c
interval_end
2016-08-08 17:00:00                                  True
2016-08-08 18:00:00                                  True
2016-08-08 19:00:00                                  True
2017-02-28 20:00:00                                  True
2017-08-04 12:00:00                                  True
...                                                   ...
2018-09-27 14:00:00                                  True
2018-09-27 15:00:00                                  True
2018-09-27 16:00:00                                  True
2018-09-27 17:00:00                                  True
2018-09-27 19:00:00                                  True

[63 rows x 1 columns]
                     9aa3b5ad-0981-1a44-d58d-e3f2d1f2d550
interval_end
2015-01-01 05:00:00                                  True
2015-01-01 06:00:00                                  True
2015-01-01 07:00:00                                  True
2015-01-01 08:00:00                                  True
2015-01-01 09:00:00                                  True
...                                                   ...
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True
2018-11-14 03:00:00                                  True
2018-11-14 04:00:00                                  True
2018-11-14 05:00:00                                  True

[2616 rows x 1 columns]
Empty DataFrame
Columns: [9e5958d7-e707-bb5f-826a-2ee8c17bf297]
Index: []
Empty DataFrame
Columns: [a03f0e3d-e65c-be54-d81f-8d29058cada5]
Index: []
Empty DataFrame
Columns: [a075bba6-b74c-d462-7462-0020ac636a3f]
Index: []
Empty DataFrame
Columns: [a2bace58-b2d3-7df7-b5d0-f471508a6819]
Index: []
Empty DataFrame
Columns: [a3af4ff8-d1aa-331b-d3fd-814b84257c56]
Index: []
Empty DataFrame
Columns: [a4025fa5-e903-6079-7f04-38357974d0e0]
Index: []
                     a8a44573-c3c1-c4d4-c0bb-03bb7ecddace
interval_end
2017-08-01 15:00:00                                  True
2017-08-01 16:00:00                                  True
2017-08-01 17:00:00                                  True
2017-08-01 18:00:00                                  True
2017-08-01 19:00:00                                  True
...                                                   ...
2018-09-24 20:00:00                                  True
2018-09-24 21:00:00                                  True
2018-09-24 23:00:00                                  True
2018-09-25 00:00:00                                  True
2018-09-25 01:00:00                                  True

[1386 rows x 1 columns]

                     ab2b089d-89fb-c0dc-85db-a37aea780a0e
interval_end
2015-05-15 12:00:00                                  True
2015-05-18 13:00:00                                  True
2015-05-18 14:00:00                                  True
2015-05-18 16:00:00                                  True
2015-05-18 17:00:00                                  True
...                                                   ...
2018-10-03 13:00:00                                  True
2018-10-10 12:00:00                                  True
2018-10-11 14:00:00                                  True
2018-10-11 15:00:00                                  True
2018-10-11 17:00:00                                  True

[779 rows x 1 columns]
                     ab2b089d-89fb-c0dc-85db-a37aea780a0e
interval_end
2015-05-15 12:00:00                                  True
2015-05-18 13:00:00                                  True
2015-05-18 14:00:00                                  True
2015-05-18 16:00:00                                  True
2015-05-18 17:00:00                                  True
...                                                   ...
2018-10-03 13:00:00                                  True
2018-10-10 12:00:00                                  True
2018-10-11 14:00:00                                  True
2018-10-11 15:00:00                                  True
2018-10-11 17:00:00                                  True

[779 rows x 1 columns]
Empty DataFrame
Columns: [b3419bd8-785d-6ca5-3326-7219ad96c641]
Index: []
                     b6fd0560-0ae2-f650-2d0c-0d92e988af6e
interval_end
2015-01-01 12:00:00                                  True
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
...                                                   ...
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True

[1681 rows x 1 columns]
                     b6fd0560-0ae2-f650-2d0c-0d92e988af6e
interval_end
2015-01-01 12:00:00                                  True
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
...                                                   ...
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True

[1681 rows x 1 columns]
Empty DataFrame
Columns: [b7386659-1010-f92c-4f4f-31b5b1f907c5]
Index: []
Empty DataFrame
Columns: [b8ec0850-c5ce-1579-5438-8d1247f0ff16]
Index: []
                     bb6d4ebb-6353-7fca-87f2-d4edbf573fcc
interval_end
2015-03-16 11:00:00                                  True
2015-03-21 11:00:00                                  True
2015-03-21 12:00:00                                  True
2015-03-21 13:00:00                                  True
2015-03-21 14:00:00                                  True
...                                                   ...
2018-10-16 13:00:00                                  True
2018-10-23 13:00:00                                  True
2018-10-30 13:00:00                                  True
2018-11-06 13:00:00                                  True
2018-11-13 13:00:00                                  True

[300 rows x 1 columns]
                     bb6d4ebb-6353-7fca-87f2-d4edbf573fcc
interval_end
2015-03-16 11:00:00                                  True
2015-03-21 11:00:00                                  True
2015-03-21 12:00:00                                  True
2015-03-21 13:00:00                                  True
2015-03-21 14:00:00                                  True
...                                                   ...
2018-10-16 13:00:00                                  True
2018-10-23 13:00:00                                  True
2018-10-30 13:00:00                                  True
2018-11-06 13:00:00                                  True
2018-11-13 13:00:00                                  True

[300 rows x 1 columns]
                     c388dd30-eaeb-dcfe-f76e-e2e6ebf83ce1
interval_end
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
2015-01-01 16:00:00                                  True
2015-01-01 17:00:00                                  True
2015-01-02 16:00:00                                  True
...                                                   ...
2018-11-08 17:00:00                                  True
2018-11-09 16:00:00                                  True
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True

[322 rows x 1 columns]
                     c478ba56-575c-c594-b016-7d3061bd9b3b
interval_end
2017-08-01 15:00:00                                  True
2017-08-01 16:00:00                                  True
2017-08-01 17:00:00                                  True
2017-08-01 18:00:00                                  True
2017-08-01 19:00:00                                  True
...                                                   ...
2018-08-30 19:00:00                                  True
2018-08-30 20:00:00                                  True
2018-08-30 21:00:00                                  True
2018-08-31 00:00:00                                  True
2018-08-31 01:00:00                                  True

[1345 rows x 1 columns]
                     c8457bd6-c454-d94d-393e-4561f0599a06
interval_end
2015-01-01 10:00:00                                  True
2015-01-01 11:00:00                                  True
2015-01-01 12:00:00                                  True
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
...                                                   ...
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True
2018-11-13 20:00:00                                  True
2018-11-13 21:00:00                                  True
2018-11-13 22:00:00                                  True

[1566 rows x 1 columns]
Empty DataFrame
Columns: [c966b497-d639-dadc-60b5-248687103a2d]
Index: []
                     cb8d68c3-d6e6-215a-eca2-b969bed491af
interval_end
2018-10-12 05:00:00                                  True
2018-10-12 06:00:00                                  True
2018-10-12 07:00:00                                  True
2018-10-12 08:00:00                                  True
2018-10-12 09:00:00                                  True
...                                                   ...
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True
2018-11-14 03:00:00                                  True
2018-11-14 04:00:00                                  True
2018-11-14 05:00:00                                  True

[793 rows x 1 columns]
              cc7bb9d3-3ef7-979e-1603-70fa8dbcb70e
interval_end
2015-01-02                                    True
2015-01-03                                    True
2015-01-04                                    True
2015-01-06                                    True
2015-01-07                                    True
...                                            ...
2018-11-09                                    True
2018-11-10                                    True
2018-11-11                                    True
2018-11-13                                    True
2018-11-14                                    True

[168 rows x 1 columns]

                     cd72b978-a4fa-c81e-6e90-14892bde8473
interval_end
2015-04-03 17:00:00                                  True
2015-07-18 18:00:00                                  True
2015-07-18 20:00:00                                  True
2015-07-18 22:00:00                                  True
2015-07-18 23:00:00                                  True
...                                                   ...
2018-11-13 19:00:00                                  True
2018-11-13 20:00:00                                  True
2018-11-13 21:00:00                                  True
2018-11-13 22:00:00                                  True
2018-11-13 23:00:00                                  True

[451 rows x 1 columns]
                     cd72b978-a4fa-c81e-6e90-14892bde8473
interval_end
2015-04-03 17:00:00                                  True
2015-07-18 18:00:00                                  True
2015-07-18 20:00:00                                  True
2015-07-18 22:00:00                                  True
2015-07-18 23:00:00                                  True
...                                                   ...
2018-11-13 19:00:00                                  True
2018-11-13 20:00:00                                  True
2018-11-13 21:00:00                                  True
2018-11-13 22:00:00                                  True
2018-11-13 23:00:00                                  True

[451 rows x 1 columns]
                     ce975f7d-c364-6d48-0a2c-ba17b480fe8c
interval_end
2015-12-12 13:00:00                                  True
2016-02-10 20:00:00                                  True
2016-02-10 21:00:00                                  True
2016-07-18 13:00:00                                  True
2016-07-19 12:00:00                                  True
...                                                   ...
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True
2018-11-14 03:00:00                                  True
2018-11-14 04:00:00                                  True
2018-11-14 05:00:00                                  True

[587 rows x 1 columns]
                     ceecdd19-18fd-a6ed-ddd0-30f2a6af6b5b
interval_end
2015-01-01 11:00:00                                  True
2015-01-01 12:00:00                                  True
2015-01-01 13:00:00                                  True
2015-01-01 14:00:00                                  True
2015-01-01 15:00:00                                  True
...                                                   ...
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True
2018-11-13 19:00:00                                  True
2018-11-13 20:00:00                                  True

[1175 rows x 1 columns]
                     d4657704-6015-5cc2-1293-c4f85d4ef86e
interval_end
2015-01-01 17:00:00                                  True
2015-01-01 18:00:00                                  True
2015-01-01 19:00:00                                  True
2015-01-01 20:00:00                                  True
2015-01-01 21:00:00                                  True
...                                                   ...
2018-11-13 21:00:00                                  True
2018-11-13 22:00:00                                  True
2018-11-13 23:00:00                                  True
2018-11-14 00:00:00                                  True
2018-11-14 01:00:00                                  True

[1512 rows x 1 columns]
Empty DataFrame
Columns: [d5e319d6-b7e6-f902-8aa7-a740ffdf3ef6]
Index: []
                     d66979ba-4d38-6ebc-865b-e9e28936f289
interval_end
2015-05-12 02:00:00                                  True
2015-05-12 03:00:00                                  True
2015-05-12 04:00:00                                  True
2015-05-12 05:00:00                                  True
2015-05-12 06:00:00                                  True
...                                                   ...
2018-11-14 01:00:00                                  True
2018-11-14 02:00:00                                  True
2018-11-14 03:00:00                                  True
2018-11-14 04:00:00                                  True
2018-11-14 05:00:00                                  True

[944 rows x 1 columns]
Empty DataFrame
Columns: [d787f244-dfa2-59b2-d1e2-c5156e632285]
Index: []
Empty DataFrame
Columns: [d8db3e51-15b2-6789-eccc-0d0573239b2f]
Index: []
Empty DataFrame
Columns: [dbea811b-92f8-4e35-432c-9a7d19680a6d]
Index: []
                     dc59faa0-5478-3c1a-9d24-e0c6eb7a6c4e
interval_end
2017-08-02 19:00:00                                  True
2017-08-02 20:00:00                                  True
2017-08-04 01:00:00                                  True
2017-08-04 19:00:00                                  True
2017-08-04 20:00:00                                  True
...                                                   ...
2018-09-15 19:00:00                                  True
2018-09-15 20:00:00                                  True
2018-09-16 19:00:00                                  True
2018-09-16 20:00:00                                  True
2018-09-16 21:00:00                                  True

[131 rows x 1 columns]
Empty DataFrame
Columns: [dcfda865-19c7-db9d-79f7-62975d5e11d5]
Index: []
                     de6f7118-06d2-45e8-1a7a-b30e07e233f7
interval_end
2015-01-02 00:00:00                                  True
2015-01-02 01:00:00                                  True
2015-01-03 00:00:00                                  True
2015-01-03 01:00:00                                  True
2015-01-03 23:00:00                                  True
...                                                   ...
2018-11-13 00:00:00                                  True
2018-11-13 01:00:00                                  True
2018-11-13 23:00:00                                  True
2018-11-14 00:00:00                                  True
2018-11-14 01:00:00                                  True

[388 rows x 1 columns]
Empty DataFrame
Columns: [debc4593-d7e7-c1ae-f268-f6944c531e3f]
Index: []
Empty DataFrame
Columns: [e4bf9a40-a95c-6488-cc12-9dfdeb781be6]
Index: []
Empty DataFrame
Columns: [e5d06e7f-d057-24d9-b417-118c206cbd7e]
Index: []
                     e7d819a2-4382-e7d1-a267-069c96a54333
interval_end
2017-09-01 23:00:00                                  True
2017-09-02 00:00:00                                  True
2017-09-02 01:00:00                                  True
2017-09-02 23:00:00                                  True
2017-09-03 00:00:00                                  True
...                                                   ...
2018-08-31 18:00:00                                  True
2018-08-31 19:00:00                                  True
2018-08-31 23:00:00                                  True
2018-09-01 00:00:00                                  True
2018-09-01 01:00:00                                  True

[2346 rows x 1 columns]
                     e9386ab1-439f-2878-6c65-fa440370f73b
interval_end
2015-01-01 17:00:00                                  True
2015-01-01 18:00:00                                  True
2015-01-01 19:00:00                                  True
2015-01-01 20:00:00                                  True
2015-01-01 21:00:00                                  True
...                                                   ...
2018-11-13 21:00:00                                  True
2018-11-13 22:00:00                                  True
2018-11-13 23:00:00                                  True
2018-11-14 00:00:00                                  True
2018-11-14 01:00:00                                  True

[1512 rows x 1 columns]

                     ea0bee90-5500-25e3-1483-5ca53f8b0d82
interval_end
2015-01-06 14:00:00                                  True
2015-01-06 15:00:00                                  True
2015-01-06 16:00:00                                  True
2015-01-06 17:00:00                                  True
2015-01-06 18:00:00                                  True
...                                                   ...
2018-11-13 14:00:00                                  True
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True

[177 rows x 1 columns]
                     ea0bee90-5500-25e3-1483-5ca53f8b0d82
interval_end
2015-01-06 14:00:00                                  True
2015-01-06 15:00:00                                  True
2015-01-06 16:00:00                                  True
2015-01-06 17:00:00                                  True
2015-01-06 18:00:00                                  True
...                                                   ...
2018-11-13 14:00:00                                  True
2018-11-13 15:00:00                                  True
2018-11-13 16:00:00                                  True
2018-11-13 17:00:00                                  True
2018-11-13 18:00:00                                  True

[177 rows x 1 columns]
                     eba417ce-b125-8595-6b56-11f89c2f09b8
interval_end
2017-08-01 18:00:00                                  True
2017-08-01 19:00:00                                  True
2017-08-01 20:00:00                                  True
2017-08-01 21:00:00                                  True
2017-08-01 22:00:00                                  True
...                                                   ...
2018-09-06 21:00:00                                  True
2018-09-16 18:00:00                                  True
2018-09-16 19:00:00                                  True
2018-09-16 20:00:00                                  True
2018-09-16 21:00:00                                  True

[364 rows x 1 columns]
Empty DataFrame
Columns: [eccea137-1478-4434-9694-6456ee9d4674]
Index: []
Empty DataFrame
Columns: [ee9e572d-9840-3093-811f-941b7f48e73f]
Index: []
Empty DataFrame
Columns: [f2f57d71-344e-adda-6441-3b7d6620dd40]
Index: []
Empty DataFrame
Columns: [f58c29d4-da39-b21a-6280-579f4b04af08]
Index: []
Empty DataFrame
Columns: [f642e2d0-64fb-a3a4-82a3-1e6c9374f0ae]
Index: []
                     f7cb6999-e8e4-8dc2-a609-4b1b5c0ca9c9
interval_end
2017-09-25 12:00:00                                  True
2017-09-25 16:00:00                                  True
2017-09-25 17:00:00                                  True
2017-09-25 18:00:00                                  True
2017-09-27 17:00:00                                  True
...                                                   ...
2018-09-17 17:00:00                                  True
2018-09-21 15:00:00                                  True
2018-09-21 16:00:00                                  True
2018-09-21 17:00:00                                  True
2018-09-21 18:00:00                                  True

[72 rows x 1 columns]
                     f7cb6999-e8e4-8dc2-a609-4b1b5c0ca9c9
interval_end
2017-09-25 12:00:00                                  True
2017-09-25 16:00:00                                  True
2017-09-25 17:00:00                                  True
2017-09-25 18:00:00                                  True
2017-09-27 17:00:00                                  True
...                                                   ...
2018-09-17 17:00:00                                  True
2018-09-21 15:00:00                                  True
2018-09-21 16:00:00                                  True
2018-09-21 17:00:00                                  True
2018-09-21 18:00:00                                  True

[72 rows x 1 columns]
                     f81d7812-364c-67ba-2379-bd4b8a6a87ba
interval_end
2017-08-01 12:00:00                                  True
2017-08-01 13:00:00                                  True
2017-08-01 14:00:00                                  True
2017-08-01 15:00:00                                  True
2017-08-01 16:00:00                                  True
...                                                   ...
2018-07-31 21:00:00                                  True
2018-07-31 22:00:00                                  True
2018-07-31 23:00:00                                  True
2018-08-01 00:00:00                                  True
2018-08-01 01:00:00                                  True

[3204 rows x 1 columns]
                     fa1e6d9b-9562-02aa-0a4a-3f08fdf1c960
interval_end
2017-08-04 01:00:00                                  True
2017-08-05 01:00:00                                  True
2017-08-18 01:00:00                                  True
2017-08-19 01:00:00                                  True
2017-09-27 00:00:00                                  True
2017-09-27 23:00:00                                  True
2018-01-18 02:00:00                                  True
2018-06-02 04:00:00                                  True
2018-07-01 01:00:00                                  True
2018-07-01 18:00:00                                  True
2018-07-01 19:00:00                                  True
2018-07-01 20:00:00                                  True
2018-07-01 21:00:00                                  True
2018-07-01 22:00:00                                  True
2018-07-02 12:00:00                                  True
2018-07-02 16:00:00                                  True
2018-07-02 17:00:00                                  True
2018-07-03 12:00:00                                  True
2018-07-04 19:00:00                                  True
2018-07-04 20:00:00                                  True
2018-07-05 12:00:00                                  True
2018-07-06 01:00:00                                  True
2018-07-06 12:00:00                                  True
2018-07-15 01:00:00                                  True
2018-07-17 01:00:00                                  True
2018-07-24 01:00:00                                  True
2018-07-25 01:00:00                                  True
2018-07-25 12:00:00                                  True
2018-07-27 01:00:00                                  True
2018-08-03 05:00:00                                  True
2018-08-07 01:00:00                                  True
2018-08-08 01:00:00                                  True
2018-08-16 01:00:00                                  True
2018-08-17 01:00:00                                  True
2018-08-18 01:00:00                                  True
2018-08-21 10:00:00                                  True
2018-08-28 01:00:00                                  True
2018-08-29 01:00:00                                  True
2018-08-29 12:00:00                                  True
2018-08-30 00:00:00                                  True
2018-08-30 01:00:00                                  True
2018-09-04 01:00:00                                  True
2018-09-04 12:00:00                                  True
2018-09-05 01:00:00                                  True
2018-09-06 00:00:00                                  True
2018-09-06 01:00:00                                  True
Empty DataFrame
Columns: [fa918bd3-d0f3-0e2d-08c6-875ade30fe3e]
Index: []
Empty DataFrame
Columns: [fb203000-0b6e-e587-0168-25b53c60a153]
Index: []

In [ ]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
pd.options.display.float_format = '{:.4g}'.format
import enlopy as el
from sklearn.preprocessing import MaxAbsScaler
import pickle

from adtk.data import validate_series
from adtk.detector import SeasonalAD, QuantileAD

file_name = "hourly_sampled.pkl"
open_file = open(file_name, "rb")
loaded_list = pickle.load(open_file)
open_file.close()

hourly_site_id_seasonality = pd.read_csv('hourly_siteid_seasonality_result.csv')
hourly_site_id_seasonality = hourly_site_id_seasonality[['site_id','seasonality']]


hourly_anomalies = pd.DataFrame()

for i in range(0,len(loaded_list)):
    df1= df.loc[df['site_id']== loaded_list[i]]
    df2 = hourly_site_id_seasonality.loc[hourly_site_id_seasonality['site_id']==loaded_list[i]]
    print(loaded_list[i]+' ===>')
    df1.interval_end = pd.to_datetime(df1.interval_end)
    df1.index= df1.interval_end
    df1.sort_index()
    df1 = df1['kw']
    if int(df2.seasonality.values)> 0:
        s_train = validate_series(df1)
        seasonal_ad = SeasonalAD(c=1.0, side="both")
        anomalies = seasonal_ad.fit_detect(s_train)
        hourly_anomalies = hourly_anomalies.append(anomalies.loc[anomalies.iloc[:,0] == True])
    else:
        s_train = validate_series(df1)
        quantile_ad = QuantileAD(high=0.99, low=0.01)
        anomalies = quantile_ad.fit_detect(s_train)
        hourly_anomalies = hourly_anomalies.append(anomalies.loc[anomalies.iloc[:,0] == True])